modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="potatocannon"
version="3.0.0"
displayName="Potato Cannon"
logoFile="potatocannon.png"
credits="Thanks to Surviv.io for this idea"
authors="NorthWestWind"
updateJSONURL="https://raw.githubusercontent.com/North-West-Wind/PotatoCannon/main/update.json"
displayURL="https://github.com/North-West-Wind/PotatoCannon"
description='''
This mod adds an overpowered item: Potato Cannon!

The Potato Cannon is based off the one from Surviv.io's Potato Mode.
(Not the one originates from WWII, although it is still pretty cool)

Just get potatoes and you can defeat anything!
'''
[[dependencies.potatocannon]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.potatocannon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
